from bs4 import BeautifulSoup

html_doc = """
<div class="code-body">
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"add-to-mmo": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>add-to-mmo</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Отметка 'Добавить в многоместное отправление'</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"address-changed": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>address-changed</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Адрес получателя скорректирован в процессе очистки</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"address-type-from": "DEFAULT"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>address-type-from</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-address-type" target="_blank">Тип адреса</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"address-type-to": "DEFAULT"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>address-type-to</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-address-type" target="_blank">Тип адреса</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"area-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>area-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Район отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"area-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>area-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Район</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"arrival-date": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>arrival-date</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Дата прибытия отправления в место вручения</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"avia-rate": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>avia-rate</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Авиа-сбор без НДС (для совместимости)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"avia-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>avia-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Авиа-сбор с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"avia-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>avia-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Авиа-сбор без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"barcode": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>barcode</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">ШПИ</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"batch-category": "ORDERED"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>batch-category</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-batch-category" target="_blank">Категория партии</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"batch-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>batch-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Внешний идентификатор партии заказа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"batch-status": "CREATED"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>batch-status</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-batch-status" target="_blank">Статус партии</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"bk-hash": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>bk-hash</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Хэш-код</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"branch-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>branch-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Идентификатор подразделения</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"building-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>building-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Строение отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"building-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>building-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Строение</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"completeness-checking": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>completeness-checking</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак услуги проверки комплектности</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"completeness-checking-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>completeness-checking-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку комплектности" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"completeness-checking-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>completeness-checking-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку комплектности" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"compulsory-payment": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>compulsory-payment</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">К оплате с получателя (копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"contents-checking-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>contents-checking-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"contents-checking-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>contents-checking-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"corpus-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>corpus-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Корпус отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"corpus-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>corpus-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Корпус</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"customs-declaration": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-declaration</b> - Декларация (Опционально)</span><span class="api-struct__tooltip-body">Таможенная декларация</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"certificate-number": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>certificate-number</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Сертификаты, сопровождающие отправление</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"comments": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>comments</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Комментарии</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"currency": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>currency</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/dictionary-currencies" target="_blank">Код валюты</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customs-code": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-code</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Код таможенного органа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customs-comments": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-comments</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Комментарии таможенного органа</span></p></div>
                        <div class="api-struct api-struct--extra" tabindex="0"><span class="api-struct__description col-offset-3">"customs-decision": "REJECTION"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-decision</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Решение таможенного органа = ['REJECTION', 'RELEASE_WO_CUSTOMS_DUTY', 'CUSTOMS_DUTY_REQUIRED', 'CUSTOMS_CONTROL_REQUIRED', 'RESERVE', 'RELEASE_SUSPENDED', 'RELEASE_PERIOD_PROLONGED', 'RELEASE_CUSTOMS_DUTY_PAID', 'AUTO_RELEASE_RETURN_GOODS', 'RELEASE_RETURN_GOODS', 'REJECTION_AUTO_RELEASE', 'DEPARTURE_ALLOWED', 'DEPARTURE_DENIED']</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customs-entries": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-entries</b> - Массив</span><span class="api-struct__tooltip-body">Список вложений</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"amount": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>amount</b> - Целое число</span><span class="api-struct__tooltip-body">Количество</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"country-code": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>country-code</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/dictionary-countries" target="_blank">Код страны происхождения</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"description": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>description</b> - Строка</span><span class="api-struct__tooltip-body">Наименование товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"entry-number": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>entry-number</b> - Целое число</span><span class="api-struct__tooltip-body">Порядковый номер</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"tnved-code": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>tnved-code</b> - Строка</span><span class="api-struct__tooltip-body">Код ТНВЭД</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"trademark": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>trademark</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Торговая марка</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"value": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>value</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Цена за единицу товара в копейках (вкл. НДС)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"weight": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>weight</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Вес товара (в граммах)</span></p></div>
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"decision-date": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>decision-date</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Дата решения таможенного органа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"decision-description": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>decision-description</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Описание решения таможенного органа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"entries-type": "GIFT"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>entries-type</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-entries-type" target="_blank">Категория вложения</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"fts-error": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>fts-error</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Ошибка декларирования</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"invoice-number": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>invoice-number</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Счет (номер счета-фактуры)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"ioss-code": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>ioss-code</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Регистрационный код продавца</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"license-number": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>license-number</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Лицензии, сопровождающие отправление</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"recom-description": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>recom-description</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Описание рекомендации таможенного органа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"registration-date": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>registration-date</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Дата регистрации документа таможенным органом</span></p></div>
                        <div class="api-struct api-struct--extra" tabindex="0"><span class="api-struct__description col-offset-3">"status": "NEW"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>status</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Статус декларации в процессе электронного декларирования = ['NEW', 'TRANSIT', 'IN_PROGRESS', 'DONE', 'REJECTED', 'CANCELED', 'ILLEGAL_DATA', 'FTS_ERROR']</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"with-certificate": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>with-certificate</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Приложенные документы: сертификат</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"with-invoice": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>with-invoice</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Приложенные документы: счет-фактура</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"with-license": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>with-license</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Приложенные документы: лицензия</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"declaration-status": "NEW"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>declaration-status</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-declaration-status" target="_blank">Результат электронного декларирования</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"delivery-time": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>delivery-time</b> - Примерные сроки доставки (Опционально)</span><span class="api-struct__tooltip-body">Время доставки</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"max-days": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>max-days</b> - Целое число</span><span class="api-struct__tooltip-body">Максимальное время доставки (дни)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"min-days": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>min-days</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Минимальное время доставки (дни)</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"delivery-with-cod": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>delivery-with-cod</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак оплаты при получении</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"dimension": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>dimension</b> - Размеры (Опционально)</span><span class="api-struct__tooltip-body">Линейные размеры</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"height": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>height</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Линейная высота (сантиметры)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"length": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>length</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Линейная длина (сантиметры)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"width": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>width</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Линейная ширина (сантиметры)</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"dimension-type": "S"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>dimension-type</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-dimension-type" target="_blank">Типоразмер</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"easy-return-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>easy-return-rate-with-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Сбор за "Лёгкий возврат" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"easy-return-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>easy-return-rate-wo-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Сбор за "Лёгкий возврат" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"ecom-data": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>ecom-data</b> - Данные ЕКОМ (Опционально)</span><span class="api-struct__tooltip-body">Данные ЕКОМ</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"delivery-point-index": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>delivery-point-index</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Идентификатор пункта выдачи</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"delivery-point-type": "DELIVERY_POINT"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>delivery-point-type</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-delivery-point-type" target="_blank">Тип пункта выдачи</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"identity-methods": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>identity-methods</b> - Массив (Опционально)</span><span class="api-struct__tooltip-body">Методы идентификации личности</span></p></div>
                        <div class="api-struct"><span class=" col-offset-4">"WITHOUT_IDENTIFICATION"</span></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"services": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>services</b> - Массив (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-ecom-services" target="_blank">Коды видов сервиса</a></span></p></div>
                        <div class="api-struct"><span class=" col-offset-4">"WITHOUT_SERVICE"</span></div>
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"electronic-notification-history": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>electronic-notification-history</b> - История электронной нотификации (Опционально)</span><span class="api-struct__tooltip-body">История электронной нотификации</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"items": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>items</b> - Массив</span><span class="api-struct__tooltip-body">Список вложений</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"has-external-resource": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>has-external-resource</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак наличия внешнего ресурса</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"is-download": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>is-download</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак скачивался ли ЭУВ клиентом</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"oper-attr": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>oper-attr</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Атрибут операции</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"oper-date": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>oper-date</b> - Строка</span><span class="api-struct__tooltip-body">Дата и время операции</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"oper-type": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>oper-type</b> - Целое число</span><span class="api-struct__tooltip-body">Тип операции</span></p></div>
                        
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"envelope-type": "C4"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>envelope-type</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-envelope-type" target="_blank">Тип конверта - ГОСТ Р 51506-99</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"fiscal-data": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>fiscal-data</b> - Фискальные данные (Опционально)</span><span class="api-struct__tooltip-body">Фискальные данные</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customer-email": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customer-email</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Адрес электронной почты плательщика</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customer-inn": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customer-inn</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">ИНН юридического лица покупателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customer-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customer-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Наименование юридического лица покупателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"customer-phone": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customer-phone</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Телефон плательщика</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"fiscal-payments": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>fiscal-payments</b> - Массив (Опционально)</span><span class="api-struct__tooltip-body">Средства, использованные при оплате</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"payment-amount": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payment-amount</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сумма оплаты платежным средством,(копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"payment-kind": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payment-kind</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Вид платежного средства</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"payment-type": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payment-type</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Тип платежного средства</span></p></div>
                        
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"fragile-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>fragile-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за отметку "Осторожно/Хрупкое"</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"fragile-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>fragile-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за отметку "Осторожно/Хрупкое" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"functionality-checking-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>functionality-checking-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений с проверкой работоспособности" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"functionality-checking-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>functionality-checking-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений с проверкой работоспособности" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"given-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>given-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Имя получателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"goods": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>goods</b> - Товарное вложение РПО (Опционально)</span><span class="api-struct__tooltip-body">Товарное вложение РПО</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"items": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>items</b> - Массив</span><span class="api-struct__tooltip-body">Список вложений</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"category-feature": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>category-feature</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Категория товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"code": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>code</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Код (маркировка) товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"country-code": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>country-code</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/dictionary-countries" target="_blank">Код страны происхождения</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"customs-declaration-number": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>customs-declaration-number</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Номер таможенной декларации</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"description": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>description</b> - Строка</span><span class="api-struct__tooltip-body">Наименование товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"excise": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>excise</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Акциз (копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"goods-type": "GOODS"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>goods-type</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-goods-type" target="_blank">Тип вложения</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"id": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>id</b> - Целое число</span><span class="api-struct__tooltip-body">Номер товара в списке вложений</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"insr-value": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>insr-value</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Объявленная ценность (копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"item-number": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>item-number</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Номенклатура (артикул) товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"lineattr": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>lineattr</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-lineattr" target="_blank">Признак предмета расчета</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"payattr": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payattr</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-payattr" target="_blank">Признак способа расчета</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"quantity": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>quantity</b> - Число</span><span class="api-struct__tooltip-body">Количество товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"returned": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>returned</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Статус возврата, вложения(ЕКОМ)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"supplier-inn": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>supplier-inn</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">ИНН поставщика товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"supplier-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>supplier-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Наименование поставщика товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"supplier-phone": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>supplier-phone</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Телефон поставщика товара</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"value": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>value</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Цена за единицу товара в копейках (вкл. НДС)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"vat-rate": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>vat-rate</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Ставка НДС: Без НДС(-1), 0, 10, 110, 20, 120</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-5">"weight": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>weight</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Вес товара (в граммах)</span></p></div>
                        
                        
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"ground-rate": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>ground-rate</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сбор за доставку наземно без НДС (для совместимости)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"ground-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>ground-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сбор за доставку наземно с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"ground-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>ground-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сбор за доставку наземно без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"group-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>group-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Наименование группы</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"hotel-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>hotel-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Название гостиницы отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"hotel-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>hotel-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Название гостиницы</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"house-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>house-from</b> - Строка</span><span class="api-struct__tooltip-body">Часть адреса: Номер здания отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"house-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>house-to</b> - Строка</span><span class="api-struct__tooltip-body">Часть адреса: Номер здания</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"human-operation-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>human-operation-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Наименование операции</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"hyper-local-status": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>hyper-local-status</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Статус по гиперлокальной доставке. См. <a href="#/enums-hyper-local-status" target="_blank">Статус по гиперлокальной доставке</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"id": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>id</b> - Целое число</span><span class="api-struct__tooltip-body">Номер товара в списке вложений</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"in-mmo": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>in-mmo</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Отправление в составе ММО</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"index-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>index-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Почтовый индекс отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"index-to": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>index-to</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Почтовый индекс</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"inner-num": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>inner-num</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Дополнительный идентификатор отправления</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"insr-rate": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>insr-rate</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Плата за ОЦ без НДС (для совместимости)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"insr-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>insr-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Плата за ОЦ с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"insr-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>insr-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Плата за ОЦ без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"insr-value": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>insr-value</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Объявленная ценность (копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"inventory-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>inventory-rate-with-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Надбавка за "Опись вложения" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"inventory-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>inventory-rate-wo-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Надбавка за "Опись вложения" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"is-deleted": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>is-deleted</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Заказ удален?</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"last-oper-attr": "UNKNOWN"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>last-oper-attr</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-base-last-oper-attr" target="_blank">Атрибут последней операции из трекинга</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"last-oper-type": "UNKNOWN"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>last-oper-type</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-base-last-oper-type" target="_blank">Тип последней операции из трекинга</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"legal-hid": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>legal-hid</b> - Строка</span><span class="api-struct__tooltip-body">Почта ID HID юридического лица</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"letter-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>letter-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Литера отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"letter-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>letter-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Литера</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"linked-barcode": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>linked-barcode</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">ШПИ связанного отправления</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"location-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>location-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Микрорайон отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"location-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>location-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Микрорайон</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mail-category": "SIMPLE"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mail-category</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-base-mail-category" target="_blank">Категория РПО</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mail-direct": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mail-direct</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/dictionary-countries" target="_blank">Код страны</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mail-rank": "WO_RANK"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mail-rank</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-mail-rank" target="_blank">Код разряда почтового отправления</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mail-type": "UNDEFINED"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mail-type</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-base-mail-type" target="_blank">Вид РПО</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mass": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mass</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Вес РПО (в граммах)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mass-rate": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mass-rate</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Почтовый сбор без НДС (для совместимости)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mass-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mass-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Почтовый сбор с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mass-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mass-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Почтовый сбор без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"middle-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>middle-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Отчество получателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"mpo-declaration": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>mpo-declaration</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Данные таможенной декларации в формате XML (кодировка UTF-8, структура согласно РТМ 0030.14-16 [4]), закодированные в строку Base64</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"notice-payment-method": "CASHLESS"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>notice-payment-method</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body"><a href="#/enums-payment-methods" target="_blank">Способ оплаты</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"notice-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>notice-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за уведомление о вручении с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"notice-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>notice-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за уведомление о вручении без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"num-address-type-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>num-address-type-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Номер для а/я, войсковая часть, войсковая часть ЮЯ, полевая почта отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"num-address-type-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>num-address-type-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Номер для а/я, войсковая часть, войсковая часть ЮЯ, полевая почта</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"office-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>office-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Офис отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"office-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>office-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Офис</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"online-payment-mark": {</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>online-payment-mark</b> - Знак онлайн оплаты (Опционально)</span><span class="api-struct__tooltip-body">Знак онлайн оплаты</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"index-oper": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>index-oper</b> - Строка</span><span class="api-struct__tooltip-body">Индекс ОПС приёма</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"online-payment-mark-id": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>online-payment-mark-id</b> - Строка</span><span class="api-struct__tooltip-body">Уникальный идентификатор ЗОО</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-3">"value": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>value</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Цена за единицу товара в копейках (вкл. НДС)</span></p></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"order-num": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>order-num</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Номер заказа. Внешний идентификатор заказа, который формируется отправителем</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"oversize-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>oversize-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за негабарит при весе более 10кг с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"oversize-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>oversize-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за негабарит при весе более 10кг без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"partial-redemption-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>partial-redemption-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Частичный выкуп" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"partial-redemption-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>partial-redemption-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Частичный выкуп" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"payment": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payment</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сумма наложенного платежа (копейки)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"payment-method": "CASHLESS"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>payment-method</b> - Строка</span><span class="api-struct__tooltip-body">Способ оплаты. См. <a href="#/enums-payment-methods" target="_blank">Способ оплаты</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"place-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>place-from</b> - Строка</span><span class="api-struct__tooltip-body">Населенный пункт отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"place-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>place-to</b> - Строка</span><span class="api-struct__tooltip-body">Населенный пункт</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"pochtaid-hid": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>pochtaid-hid</b> - Строка</span><span class="api-struct__tooltip-body">Почта ID HID</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"postmarks": [</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>postmarks</b> - Массив</span><span class="api-struct__tooltip-body"><a href="#/enums-base-postmarks" target="_blank">Коды отметок внутренних и международных отправлений</a></span></p></div>
                        <div class="api-struct"><span class=" col-offset-3">"WITHOUT_MARK"</span></div>
                        
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"postoffice-code": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>postoffice-code</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Индекс места приема</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"pre-postal-preparation": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>pre-postal-preparation</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Отметка 'Предпостовая подготовка'</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"pre-postal-preparation-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>pre-postal-preparation-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Предпочтовая подготовка" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"pre-postal-preparation-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>pre-postal-preparation-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Предпочтовая подготовка" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"prepaid-amount": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>prepaid-amount</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Сумма частичной предоплаты</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"raw-address": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>raw-address</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Необработанный адрес получателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"recipient-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>recipient-name</b> - Строка</span><span class="api-struct__tooltip-body">Наименование получателя одной строкой (ФИО, наименование организации)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"region-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>region-from</b> - Строка</span><span class="api-struct__tooltip-body">Область, регион отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"region-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>region-to</b> - Строка</span><span class="api-struct__tooltip-body">Область, регион</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"renewal-shelf-life": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>renewal-shelf-life</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак подачи заявления на продление срока хранения</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"returned-partial": true</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>returned-partial</b> - Логические: true или false (Опционально)</span><span class="api-struct__tooltip-body">Признак частичного возврата</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"room-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>room-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Номер помещения отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"room-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>room-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Номер помещения</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"sender-comment": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>sender-comment</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Комментарий отправитяля к ЭУВ</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"sender-name": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>sender-name</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Наименование отправителя одной строкой (ФИО, наименование организации)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"shelf-life-days": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>shelf-life-days</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Срок хранения отправления от 15 до 60 дней</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"slash-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>slash-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Дробь отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"slash-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>slash-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Дробь</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"sms-notice-recipient": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>sms-notice-recipient</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Признак услуги SMS уведомления</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"sms-notice-recipient-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>sms-notice-recipient-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Пакет смс получателю" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"sms-notice-recipient-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>sms-notice-recipient-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Пакет смс получателю" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"str-index-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>str-index-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Почтовый индекс (буквенно-цифровой)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"street-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>street-from</b> - Строка</span><span class="api-struct__tooltip-body">Часть адреса: Улица отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"street-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>street-to</b> - Строка</span><span class="api-struct__tooltip-body">Часть адреса: Улица</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"surname": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>surname</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Фамилия получателя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"tel-address": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>tel-address</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Телефон получателя (может быть обязательным для некоторых типов отправлений)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"tel-address-from": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>tel-address-from</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Телефон отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"total-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>total-rate-wo-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Плата всего без НДС (коп)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"total-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>total-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Всего НДС (коп)</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"track-by-group": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>track-by-group</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Услуга 'Отслеживание группой'</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"transport-type": "SURFACE"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>transport-type</b> - Строка</span><span class="api-struct__tooltip-body"><a href="#/enums-base-transport-type" target="_blank">Вид транспортировки</a></span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"version": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>version</b> - Целое число</span><span class="api-struct__tooltip-body">Версия заказа</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"vladenie-from": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>vladenie-from</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Владение отправителя</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"vladenie-to": "string"</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>vladenie-to</b> - Строка (Опционально)</span><span class="api-struct__tooltip-body">Часть здания: Владение</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"vsd-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>vsd-rate-with-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Надбавка за "Возврат сопроводительных документов" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"vsd-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>vsd-rate-wo-vat</b> - Целое число</span><span class="api-struct__tooltip-body">Надбавка за "Возврат сопроводительных документов" без НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"with-fitting-rate-with-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>with-fitting-rate-with-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений с примеркой" с НДС</span></p></div>
                        <div class="api-struct" tabindex="0"><span class="api-struct__description col-offset-2">"with-fitting-rate-wo-vat": 0</span><p class="api-struct__tooltip"><span class="api-struct__tooltip-header"><b>with-fitting-rate-wo-vat</b> - Целое число (Опционально)</span><span class="api-struct__tooltip-body">Надбавка за "Проверку вложений с примеркой" без НДС</span></p></div>
                        
                        

                    </div>
"""

soup = BeautifulSoup(html_doc, 'html.parser')

description = [i.text for i in soup.find_all('span', class_='api-struct__description')]
tooltip_body = [i.text for i in soup.find_all('span', class_='api-struct__tooltip-body')]

description = [i.split(':')[0] for i in description]

for i, desc in enumerate(description):
    print(f'{desc}: "{tooltip_body[i]}",')
