# Generated by Django 5.0.2 on 2024-03-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OzonFBOPosting',
            fields=[
                ('posting_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_type', models.CharField(blank=True, max_length=200, null=True)),
                ('is_legal', models.BooleanField()),
                ('is_premium', models.BooleanField()),
                ('payment_type_group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse_id', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cancel_reason_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('in_process_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.BigIntegerField()),
                ('order_number', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OzonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30)),
                ('client_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OzonAllPostingFinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Тенге'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Юань')], max_length=3)),
                ('client_price', models.CharField(max_length=255)),
                ('commission_amount', models.FloatField()),
                ('commission_percent', models.IntegerField()),
                ('commissions_currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Тенге'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Юань')], max_length=3)),
                ('marketplace_service_item_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_direct_flow_trans', models.FloatField()),
                ('marketplace_service_item_dropoff_ff', models.FloatField()),
                ('marketplace_service_item_dropoff_pvz', models.FloatField()),
                ('marketplace_service_item_dropoff_sc', models.FloatField()),
                ('marketplace_service_item_fulfillment', models.FloatField()),
                ('marketplace_service_item_pickup', models.FloatField()),
                ('marketplace_service_item_return_after_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_return_flow_trans', models.FloatField()),
                ('marketplace_service_item_return_not_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_return_part_goods_customer', models.FloatField()),
                ('old_price', models.FloatField()),
                ('payout', models.FloatField()),
                ('price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_discount_percent', models.FloatField()),
                ('total_discount_value', models.FloatField()),
                ('fbo_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonfboposting')),
            ],
        ),
        migrations.CreateModel(
            name='Ozon_FBO_Posting_Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('digital_codes', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('offer_id', models.CharField(max_length=200)),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Тенге'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Юань')], max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField()),
                ('fbo_postings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonfboposting')),
            ],
        ),
        migrations.CreateModel(
            name='OzonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('offer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_fbo_visible', models.BooleanField(null=True)),
                ('is_fbs_visible', models.BooleanField(null=True)),
                ('archived', models.BooleanField(null=True)),
                ('is_discounted', models.BooleanField(null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonsettings')),
            ],
        ),
        migrations.AddField(
            model_name='ozonfboposting',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonsettings'),
        ),
        migrations.CreateModel(
            name='OzonWarehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('has_entrusted_acceptance', models.BooleanField()),
                ('is_rfbs', models.BooleanField()),
                ('can_print_act_in_advance', models.BooleanField()),
                ('dropoff_point_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_timeslot_id', models.IntegerField(blank=True, null=True)),
                ('first_mile_is_changing', models.BooleanField()),
                ('first_mile_type', models.CharField(max_length=255)),
                ('has_postings_limit', models.BooleanField()),
                ('is_karantin', models.BooleanField()),
                ('is_kgt', models.BooleanField()),
                ('is_timetable_editable', models.BooleanField()),
                ('min_postings_limit', models.IntegerField()),
                ('postings_limit', models.IntegerField()),
                ('min_working_days', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('working_days', models.CharField(max_length=255)),
                ('is_able_to_set_price', models.BooleanField(null=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonsettings')),
            ],
        ),
        migrations.CreateModel(
            name='OzonDeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('cutoff', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('provider_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('EDITED', 'Редактируется'), ('ACTIVE', 'Активный'), ('DISABLED', 'Неактивный')], max_length=255)),
                ('template_id', models.BigIntegerField()),
                ('updated_at', models.DateTimeField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonsettings')),
                ('warehouse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonwarehouse')),
            ],
        ),
    ]
