# Generated by Django 5.0.2 on 2024-03-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OzonAllPostingFinancialProduct',
        ),
    ]
