# Generated by Django 5.0.2 on 2024-03-08 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0002_delete_ozonallpostingfinancialproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzonAllPostingFinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Тенге'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Юань')], max_length=3)),
                ('client_price', models.CharField(max_length=255)),
                ('commission_amount', models.FloatField()),
                ('commission_percent', models.IntegerField()),
                ('commissions_currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('KZT', 'Тенге'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Юань')], max_length=3)),
                ('marketplace_service_item_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_direct_flow_trans', models.FloatField()),
                ('marketplace_service_item_dropoff_ff', models.FloatField()),
                ('marketplace_service_item_dropoff_pvz', models.FloatField()),
                ('marketplace_service_item_dropoff_sc', models.FloatField()),
                ('marketplace_service_item_fulfillment', models.FloatField()),
                ('marketplace_service_item_pickup', models.FloatField()),
                ('marketplace_service_item_return_after_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_return_flow_trans', models.FloatField()),
                ('marketplace_service_item_return_not_deliv_to_customer', models.FloatField()),
                ('marketplace_service_item_return_part_goods_customer', models.FloatField()),
                ('old_price', models.FloatField()),
                ('payout', models.FloatField()),
                ('price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_discount_percent', models.FloatField()),
                ('total_discount_value', models.FloatField()),
                ('fbo_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonfboposting')),
            ],
        ),
    ]
