# Generated by Django 5.0.2 on 2024-03-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0003_ozonallpostingfinancialproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ozonallpostingfinancialproduct',
            name='fbo_posting',
        ),
    ]
