# Generated by Django 5.0.2 on 2024-03-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0004_remove_ozonallpostingfinancialproduct_fbo_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozonallpostingfinancialproduct',
            name='fbo_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonfboposting'),
        ),
    ]
