# Generated by Django 5.0.2 on 2024-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0006_ozon_fbs_posting_ozon_fbs_deliverymethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozon_fbs_posting',
            name='delivering_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ozon_fbs_posting',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
