# Generated by Django 5.0.2 on 2024-03-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0008_remove_ozon_fbs_deliverymethod_fbs_posting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon_fbs_deliverymethod',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozon_app.ozonsettings'),
        ),
    ]
