# Generated by Django 5.0.2 on 2024-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_app', '0010_ozonallpostingfinancialproduct_fbs_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ozon_fbs_posting',
            name='shipment_posting_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ozon_fbs_posting',
            name='system_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
