# Generated by Django 4.2.7 on 2024-01-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ozon_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30)),
                ('client_key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
