# Generated by Django 4.2.7 on 2024-02-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildBerries_Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeId', models.IntegerField()),
                ('number', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('supplierArticle', models.CharField(max_length=255)),
                ('techSize', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField()),
                ('dateClose', models.DateTimeField()),
                ('warehouseName', models.CharField(max_length=255)),
                ('nmId', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WildBerries_Offices',
            fields=[
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WildBerries_ParentCategory',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isVisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildBerries_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WildBerries_Seller_Offices',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('officeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildberries.wildberries_offices')),
            ],
        ),
        migrations.CreateModel(
            name='WildBerries_ContentObjects',
            fields=[
                ('objectID', models.IntegerField(primary_key=True, serialize=False)),
                ('objectName', models.CharField(max_length=255)),
                ('parentName', models.CharField(max_length=255)),
                ('isVisible', models.BooleanField(default=True)),
                ('parentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildberries.wildberries_parentcategory')),
            ],
        ),
    ]
