# Generated by Django 4.2.7 on 2024-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildberries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildBerries_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('warehouseName', models.CharField(max_length=255)),
                ('countryName', models.CharField(max_length=255)),
                ('oblastOkrugName', models.CharField(max_length=255)),
                ('regionName', models.CharField(max_length=255)),
                ('supplierArticle', models.CharField(max_length=255)),
                ('nmId', models.IntegerField()),
                ('barcode', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('techSize', models.CharField(max_length=255)),
                ('incomeID', models.IntegerField()),
                ('isSupply', models.BooleanField()),
                ('isRealization', models.BooleanField()),
                ('totalPrice', models.FloatField()),
                ('discountPercent', models.FloatField()),
                ('spp', models.FloatField()),
                ('finishedPrice', models.FloatField()),
                ('priceWithDisc', models.FloatField()),
                ('isCancel', models.BooleanField()),
                ('cancelDate', models.DateTimeField()),
                ('orderType', models.CharField(max_length=255)),
                ('sticker', models.CharField(max_length=255)),
                ('gNumber', models.CharField(max_length=255)),
                ('srid', models.CharField(max_length=255)),
            ],
        ),
    ]
